Converte e formata escala e valores da temperatura para grau celsius
parlametria/leggo-painel pull request #203
Opened 2020-12-18 00:43 UTC by Andrezj

2020-12-23 14:38 UTC, gileadekelvin submitted a review, later dismissed

2020-12-23 17:47 UTC, gileadekelvin commented
PR não pode ser aprovado enquanto a questão do valor de conversão para a tempetura 100 °C não tiver sido definida.

2020-12-23 17:48 UTC, gileadekelvin reviewed
PR não pode ser aprovado enquanto a questão do número padrão para 100°C não tiver sido definida.

2021-03-09 19:23 UTC, jeffersonrpn requested changes

2021-03-09 19:23 UTC, jeffersonrpn commented on src/app/proposicoes/detalhes-proposicao/vis-temperatura-pressao/vis-temperatura-pressao.component.ts
> +    this.yTemperatura.domain([0, 100]);
O domínio da temperatura deve voltar a ser o máximo mesmo

2021-03-12 21:16 UTC, closed without merging