Exibe as ações legislativas da semana ao selecioná-la no gráfico de temperatura/pressão
parlametria/leggo-painel pull request #241
Opened 2021-02-24 15:26 UTC by jeffersonrpn

Depende do [PR 327](https://github.com/parlametria/leggo-backend/pull/327)

2021-02-25 20:11 UTC, gileadekelvin requested changes
Funcionou bem aqui e rápido também na interação com o gráfico! 
Escrevi algumas dúvidas que tive durante a revisão.

2021-02-25 20:11 UTC, gileadekelvin commented on src/app/proposicoes/detalhes-proposicao/vis-temperatura-pressao/vis-temperatura-pressao.component.ts
> +    // const largura = (window.innerWidth > 800) ? 800 : window.innerWidth;
Esse comentário pode ser deletado?

2021-02-25 20:11 UTC, gileadekelvin commented on src/app/proposicoes/detalhes-proposicao/vis-temperatura-pressao/vis-temperatura-pressao.component.ts
> +    // const tooltipTemperatura = this.svg.append('foreignObject')
Pelo que entendi vale a pena deixar comentado porque o tooltip pode voltar no futuro?

2021-02-25 20:11 UTC, gileadekelvin commented on src/app/proposicoes/detalhes-proposicao/vis-temperatura-pressao/vis-temperatura-pressao.component.ts
> +      // tooltipTemperaturaBody.html(`<strong class="color-temperatura">${dados[i - 1].valorTemperatura}</strong> de temperatura`);
Tooltip que pode voltar no futuro?

2021-02-25 20:11 UTC, gileadekelvin commented on src/app/shared/services/eventos.service.ts
> +      // console.log('Inicial: ');
Esse comentário pode ser removido?

2021-02-25 20:11 UTC, gileadekelvin commented on src/app/proposicoes/detalhes-proposicao/temperatura-pressao/temperatura-pressao.component.html
> +<br>
Essa sequência de <br> é para garantir o espaçamento no final da página?

2021-02-25 20:11 UTC, gileadekelvin commented on src/app/shared/services/eventos.service.ts
> +      .set('interesse', interesse)
Aqui não estava exibindo os eventos. Mas quando removi o essa linha do parâmetro do interesse funcionou. Faz sentido remover?

2021-02-25 20:11 UTC, gileadekelvin commented on src/app/proposicoes/detalhes-proposicao/detalhes-proposicao.component.ts
> +  // private groupBy = key => array =>
Esse código/comentário faz sentido manter?

2021-02-25 20:11 UTC, gileadekelvin commented on src/app/proposicoes/detalhes-proposicao/detalhes-proposicao.component.ts
> +import { EventosService } from 'src/app/shared/services/eventos.service';
O service EventosService e o model Evento estão sendo usados nesse componente?

2021-03-01 15:34 UTC, jeffersonrpn reviewed
Como o tooltip pode retornar, deixei apenas essa parte comentada.

2021-03-01 15:34 UTC, jeffersonrpn commented on src/app/proposicoes/detalhes-proposicao/detalhes-proposicao.component.ts
> +import { EventosService } from 'src/app/shared/services/eventos.service';
Removido

2021-03-01 15:34 UTC, jeffersonrpn commented on src/app/proposicoes/detalhes-proposicao/detalhes-proposicao.component.ts
> +  // private groupBy = key => array =>
Era parte de outra implementação. Removido

2021-03-01 15:34 UTC, jeffersonrpn commented on src/app/proposicoes/detalhes-proposicao/temperatura-pressao/temperatura-pressao.component.html
> +<br>
Era pra evitar um bug no scroll, mas não é mais necessário. Removido.

2021-03-01 16:09 UTC, gileadekelvin approved these changes

2021-03-01 16:09 UTC, merged