Transforma o número de temperatura e pressão, no card, para uma decimal apenas
parlametria/leggo-painel pull request #343
Opened 2021-04-20 15:20 UTC by joaolgm

Resolve issue #336

2021-04-20 20:02 UTC, gileadekelvin requested changes

2021-04-20 20:02 UTC, gileadekelvin commented on src/app/proposicoes/card-proposicao/card-proposicao.component.ts
> +    this.proposicao.ultima_pressao = parseFloat(this.proposicao.ultima_pressao.toFixed(1));
O que acha de adotar uma estratégia usando o pipe do angular? Como o que foi feito para governismo/disciplina:
https://github.com/parlametria/leggo-painel/blob/master/src/app/atividade-parlamentar/card-atividade/card-atividade.component.html#L146

2021-04-26 11:54 UTC, gileadekelvin requested changes

2021-04-26 11:54 UTC, gileadekelvin commented on src/app/proposicoes/card-proposicao/card-proposicao.component.html
> +            [label]="'Temperatura da semana: ' + (proposicao?.ultima_temperatura | number : '1.0-1')"
Aqui funcionou! O mesmo deveria ser feito para pressão?

2021-04-27 12:22 UTC, joaolgm commented on src/app/proposicoes/card-proposicao/card-proposicao.component.html
> +            [label]="'Temperatura da semana: ' + (proposicao?.ultima_temperatura | number : '1.0-1')"
Pelo que percebi, a pressão não mostra números decimais na barra

2021-04-28 12:27 UTC, gileadekelvin approved these changes

2021-04-28 12:27 UTC, merged